# Site settings
title: Sourav Debnath
description: A blog about me.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sourav Debnath
user_subtitle: Mechanical Engineer | Web Developer
user_description: Freshly graduated from IIT Madras, India
email: debnath.sourabh@gmail.com
twitter_username: souravdebnath27
github_username:  sourav27
linkedin_username:  souravdebnath
instagram_username: debu11
facebook_username: souravdebnath27

# Google-analytics
google-analytics:
  id: "UA-126572552-1"

exclude: ['vendor','package.json', 'node_modules']

sass:
  sass_dir: assets/styles
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
