# Site settings
title: Sourav Debnath
description: A portfolio page showcasing my engineering skills with greater focus on things other than them"
baseurl: "" # the subpath of your site, e.g. /blog
production_url: "https://sourav27.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
BASE_PATH: https://sourav27.github.io
# User settings
username: Sourav Debnath
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Mechanical Engineer | Web Developer | Programmer
email: debnath.sourabh@gmail.com
twitter_username: lorem_ipsum
github_username:  sourav27
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-126572552-1"

exclude: ['package.json', 'src' , 'node_modules']
